module "compute-instance" {
  source                     = "oracle-terraform-modules/compute-instance/oci"
  version                    = "2.0.2"
  assign_public_ip           = var.assign_public_ip
  attachment_type            = var.attachment_type
  block_storage_sizes_in_gbs = var.block_storage_sizes_in_gbs
  boot_volume_size_in_gbs    = var.boot_volume_size_in_gbs
  compartment_ocid           = var.compartment_ocid
  extended_metadata          = var.extended_metadata
  hostname_label             = var.hostname_label
  instance_count             = var.instance_count
  instance_display_name      = var.instance_display_name
  instance_timeout           = var.instance_timeout
  ipxe_script                = var.ipxe_script
  preserve_boot_volume       = var.preserve_boot_volume
  private_ips                = var.private_ips
  resource_platform          = var.resource_platform
  shape                      = var.shape
  skip_source_dest_check     = var.skip_source_dest_check
  source_ocid                = var.source_ocid
  source_type                = var.source_type
  ssh_authorized_keys        = var.ssh_authorized_keys
  subnet_ocids               = var.subnet_ocids
  use_chap                   = var.use_chap
  user_data                  = var.user_data
  vnic_name                  = var.vnic_name
}
