module "oke" {
  source                       = "oracle-terraform-modules/oke/oci"
  version                      = "4.4.1"
  allow_node_port_access       = var.allow_node_port_access
  allow_pod_internet_access    = var.allow_pod_internet_access
  allow_worker_internet_access = var.allow_worker_internet_access
  allow_worker_ssh_access      = var.allow_worker_ssh_access
  assign_dns                   = var.assign_dns
  cni_type                     = var.cni_type
  compartment_id               = var.compartment_id
  control_plane_allowed_cidrs  = var.control_plane_allowed_cidrs
  control_plane_type           = var.control_plane_type
  create_fss                   = var.create_fss
  enable_waf                   = var.enable_waf
  ig_route_id                  = var.ig_route_id
  internal_lb_allowed_cidrs    = var.internal_lb_allowed_cidrs
  internal_lb_allowed_ports    = var.internal_lb_allowed_ports
  label_prefix                 = var.label_prefix
  load_balancers               = var.load_balancers
  nat_route_id                 = var.nat_route_id
  public_lb_allowed_cidrs      = var.public_lb_allowed_cidrs
  public_lb_allowed_ports      = var.public_lb_allowed_ports
  subnets                      = var.subnets
  vcn_id                       = var.vcn_id
  worker_type                  = var.worker_type
}
