module "oke" {
  source                       = "oracle-terraform-modules/oke/oci"
  version                      = "5.1.7"
  autoscaler_compartments      = var.autoscaler_compartments
  cluster_id                   = var.cluster_id
  cluster_kms_key_id           = var.cluster_kms_key_id
  compartment_id               = var.compartment_id
  create_iam_autoscaler_policy = var.create_iam_autoscaler_policy
  create_iam_defined_tags      = var.create_iam_defined_tags
  create_iam_kms_policy        = var.create_iam_kms_policy
  create_iam_operator_policy   = var.create_iam_operator_policy
  create_iam_resources         = var.create_iam_resources
  create_iam_tag_namespace     = var.create_iam_tag_namespace
  create_iam_worker_policy     = var.create_iam_worker_policy
  defined_tags                 = var.defined_tags
  freeform_tags                = var.freeform_tags
  operator_volume_kms_key_id   = var.operator_volume_kms_key_id
  state_id                     = var.state_id
  tag_namespace                = var.tag_namespace
  tenancy_id                   = var.tenancy_id
  use_defined_tags             = var.use_defined_tags
  worker_compartments          = var.worker_compartments
  worker_volume_kms_key_id     = var.worker_volume_kms_key_id
}
