module "oke" {
  source                  = "oracle-terraform-modules/oke/oci"
  version                 = "5.0.0-beta.3"
  cluster_kms_key_id      = var.cluster_kms_key_id
  cluster_name            = var.cluster_name
  cluster_type            = var.cluster_type
  cni_type                = var.cni_type
  compartment_id          = var.compartment_id
  control_plane_is_public = var.control_plane_is_public
  control_plane_nsg_ids   = var.control_plane_nsg_ids
  control_plane_subnet_id = var.control_plane_subnet_id
  defined_tags            = var.defined_tags
  freeform_tags           = var.freeform_tags
  image_signing_keys      = var.image_signing_keys
  kubernetes_version      = var.kubernetes_version
  pods_cidr               = var.pods_cidr
  service_lb_subnet_id    = var.service_lb_subnet_id
  services_cidr           = var.services_cidr
  state_id                = var.state_id
  tag_namespace           = var.tag_namespace
  use_defined_tags        = var.use_defined_tags
  use_signed_images       = var.use_signed_images
  vcn_id                  = var.vcn_id
}
